name: Revert Commit

on:
  workflow_dispatch:
  # Puoi aggiungere altre opzioni di trigger se necessario

jobs:
  revert_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Revert Commit
        run: |
          git revert 000d3e2b8178575eb14413236d6feb6f2db4a5f2
          git push origin main  # Sostituisci 'main' con il nome del tuo branch
        env:
          # Aggiungi eventuali variabili di ambiente necessarie

